version: '3.8'

services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
    container_name: codespaces-app
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: codespaces-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
