version: '3.8'

services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace
    command: sleep infinity

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
